name: Bug Report
description: File a bug report
labels: [bug]
body:
- type: textarea
  attributes:
    label: Describe the bug
    description: A clear and concise description of what the bug is and what page it happens on.
  validations:
    required: true

- type: input
  attributes:
    label: Browser name and version
  validations:
    required: true
